# All possible configuration.
# For more see: http://jekyllrb.com/docs/configuration/
destination: ./_site
lsi:         false
port:        4000
highligher:  true

# Build settings
markdown:    rdiscount
rdiscount:
  extensions: [smart]

# This is the default base url path.
BASE_PATH : http://zhangtzt.github.io/

# Website title.
title : Zhang T<small>Introvert Geek Diaries</small>

# label listing. [create labels for category in folder `_label`]
# social listing. [create labels for social in folder `_label`]
collections:
  - category
  - social

# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:title

# Pagination based on number of posts
# For more see: http://jekyllrb.com/docs/pagination/
#paginate: 20
#paginate_path: "page/:num"

  ## Author Details ##
###########################
author:
# Info
  name: Zhang T
  role: Computer Programmer
  email: tao_zhang@live.com
  image: images/zhang.png
# Social
  github: zhangtzt
  twitter: 
  facebook: 
  soundcloud: 
  reddit: 
#  About
  about: "This is my-space."
# copyright
  copyright: "Some rights reserved &#169; 2020 Zhang T."

# Disable custom plugins,and ignore symbolic links..
# For more see: http://jekyllrb.com/docs/configuration/
safe:    false
# Jekyll-sitemap auto generate
# For more see: https://github.com/jekyll/jekyll-sitemap
gems:
  - jekyll-sitemap
